create table EMPLOYEE
(
	EMP_ID INT PRIMARY KEY, 
	ENAME VARCHAR(20), 
	DEPARTMENT VARCHAR(30), 
	MANAGER_ID INT,
	FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(EMP_ID)
);

use db_test;

INSERT INTO EMPLOYEE(EMP_ID, ENAME, DEPARTMENT, MANAGER_ID)
VALUES 
(1, 'A', 'AA', NULL),
(2, 'B', 'BB', 1),
(3, 'C', 'CC', 1),
(4, 'D', 'DD', 2);

SELECT E1.ENAME AS [EMPLOYEE NAME], E2.ENAME AS [MANAGER NAME],
		E1.DEPARTMENT AS [EMPLOYEE DEPARTMENT], E2.DEPARTMENT AS [MANAGER DEPARTMENT]

FROM EMPLOYEE AS E1
LEFT OUTER JOIN 
EMPLOYEE AS E2
ON
E1.MANAGER_ID = E2.EMP_ID;